name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build \
          -t chatapi-tests-$GITHUB_RUN_ID \
          --build-arg PYTHONVERSION=${{ matrix.python-version }} \
          -f tests.Dockerfile \
          .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker run chatapi-tests-$GITHUB_RUN_ID flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker run chatapi-tests-$GITHUB_RUN_ID flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest in docker-compose
      run: |
        docker-compose \
          -f tests.docker-compose.yml \
          up \
          --abort-on-container-exit \
          --exit-code-from pytest